# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ULC Project
email: info@ulcproject.com
description: > # this means to ignore newlines until "baseurl:"
  Unblocked Ledger Coin (ULC) is a payment network designed to remedy the problems of traditional blockchains — scalability, decentralization, security and long term sustainability. 
  The technology being developed for ULC can accommodate billions of daily active users and can be applied to many future global-scale decentralized applications. 
  The ULC payment network is the first application of this technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ulcproject.com" # the base hostname & protocol for your site
thumbnail: "assets/img/logo_notext.png"
# Build settings
markdown: kramdown
